# Generated by Django 4.2.16 on 2024-10-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_ascii', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('country', models.TextField()),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
    ]
